name: Backend Workflow

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
    branches: ["main"]
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
    branches: ["main"]

jobs:
  lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        working-directory: services
        run: |
          go mod download
          go generate ./...

      - name: Lint check
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.52.2"
          working-directory: services

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        working-directory: services
        run: |
          go mod download
          go generate ./...

      - name: Test
        working-directory: services
        run: |
          go test -cover ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        working-directory: services
        run: |
          go mod download
          go generate ./...

      - name: Build
        working-directory: services
        run: |
          go build -o saul server.go
